### ISSUE TITLE
Add CMS category for fellow projects

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/SDOHPlace#171]
We will be creating new pages for each of the community fellow projects, and can do this within the existing Decap CMS setup by editing this file: https://github.com/healthyregions/SDOHPlace/blob/main/public/admin/config.yml. This should be fairly straightforward through the addition of a new Collection as described here: https://decapcms.org/docs/configure-decap-cms/. Further reference for [collections](https://decapcms.org/docs/configuration-options/#collections).

The new collection could be defined something like this:

```
collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Fellow Projects" # Used in the UI
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Year"
        name: "year"
        widget: "number???"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        default: "/images/default.jpg"
```
